export const PENDING = "PENDING"

export const SET_CART_SUCCESS = "SET_CART_SUCCESS"
export const SET_CART_ERROR = "SET_CART_ERROR"

export const SET_ITEMS_SUCCESS = "SET_ITEMS_SUCCESS"
export const SET_ITEMS_ERROR = "SET_ITEMS_ERROR"
