export const ADD_PRODUCT_TO_CART = 'ADD PRODUCT TO CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE PRODUCT FROM CART';

export const FETCH_PENDING = 'FETCH PENDING';
export const FETCH_SUCCESS = 'FETCH SUCCESS';
export const FETCH_ERROR   = 'FETCH ERROR';